version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - tznind
  - jas88
  ignore:
  - dependency-name: NPOI
    versions:
    - ">= 2.5.1.a"
    - "< 2.5.2"
  - dependency-name: NPOI
    versions:
    - ">= 2.5.a"
    - "< 2.6"
  - dependency-name: System.Resources.Extensions
    versions:
    - "> 4.6.0"
    - "< 5"
