version: 1.0.{build}
init:
  - cmd: if defined APPVEYOR_PULL_REQUEST_NUMBER appveyor exit
  - git config --global core.autocrlf true
image: Visual Studio 2019
services:
  - mssql2017
  - mysql
  - postgresql101

cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

before_build:
- dotnet restore --packages ./packages
- choco install opencover.portable

build_script:
  - ps: Remove-Item "./Tests.Common/TestDatabases.txt"
  - ps: Rename-Item -Path "./Tests.Common/TestDatabases.appveyor.txt" -NewName "TestDatabases.txt"
  - ps: dotnet build HIC.DataManagementPlatform.sln /v:q
  - ps: dotnet publish "./Tools/rdmp" -r win-x64
  - ps: ./Tools/rdmp/bin/Debug/net5.0/win-x64/rdmp install localhost\SQL2017 TEST_ -D -u sa -p Password12!
  
  # Run the windows tests with a custom encryption key
  - ps: Remove-Item "./Tools/rdmp/bin/Debug/net5.0/win-x64/Databases.yaml"
  - ps: Move-Item -Path "./Tests.Common/Databases.appveyor.yaml" -Destination "./Tools/rdmp/bin/Debug/net5.0/win-x64/Databases.yaml"
  - ps: ./Tools/rdmp/bin/Debug/net5.0/win-x64/rdmp cmd CreatePrivateKey ./MyKey.key
  
  - ps: dotnet test "./Rdmp.UI.Tests/Rdmp.UI.Tests.csproj"
  
  # Run code coverage on non UI tests
  - cmd: "\"packages/opencover/4.7.922/tools/OpenCover.Console.exe\" -returntargetcode -target:\"c:/program files/dotnet/dotnet.exe\" -targetargs:\"test ./scripts/run-all-tests.proj -f net5.0 -c Release -p:BuildInParallel=false\" -filter:\"+[*Rdmp.Core*]* +[*ReusableLibraryCode*]* +[*MapsDirectlyToDatabaseTable*]* -[*Tests*]*\"  -output:coverage.xml -register:appveyor -oldStyle -hideskipped:File"
  - cmd: packages\coveralls.io\1.4.2\tools\coveralls.net.exe --opencover coverage.xml -r %COVERALLS_REPO_TOKEN%

test: off

environment:
  COVERALLS_REPO_TOKEN:
    secure: CmtrH/h57hWTM17zwN6LUKin9nzebssvZoADRZIIbj2NH//QQVoDEqF6UW8tkg4U
