PUBLISH_DIR =  ENV['PUBLISH_DIR']  || "Release" 
SOLUTION =     ENV['SOLUTION']     || "DatabaseCreation/DatabaseCreation.csproj" 
DBSERVER =     ENV['DBSERVER']     || "localhost\\sqlexpress" 
DBPREFIX =     ENV['DBPREFIX']     || "TEST_" 
PRERELEASE =   ENV['PRERELEASE']   || "false"
CANDIDATE =    ENV['CANDIDATE']    || "false"
SUFFIX =       ENV['SUFFIX']       || "develop"