using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyCompanyAttribute("HIC")]
[assembly: AssemblyVersionAttribute("0.0.0.47")]
[assembly: AssemblyFileVersionAttribute("0.0.0.47")]
[assembly: AssemblyInformationalVersionAttribute("0.0.0.4d501a2480acba1b717890996f1491327233d6e5")]
[assembly: AssemblyTitleAttribute("HIC.DataManagementPlatform")]
[assembly: AssemblyProductAttribute("HIC.DataManagementPlatform")]
[assembly: AssemblyDescriptionAttribute("HIC.DataManagementPlatform is a product of HIC - https://github.com/HicServices/R" +
    "DMP.git.")]
[assembly: AssemblyTrademarkAttribute("HIC.DataManagementPlatform - HIC")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2018 HIC, - Original author or authors")]

