using System.Data.Common;
using System.Diagnostics;
using System.IO;
using CatalogueLibrary.Data;
using CatalogueLibrary.Repositories;
using DataExportLibrary.Data.DataTables;
using DataExportLibrary.ExtractionTime;
using DataExportLibrary.Interfaces.Data.DataTables;
using ReusableLibraryCode.DataAccess;

namespace DataExportLibrary.DataRelease
{
    /// <summary>
    /// Determines whether a given ExtractableDataSet in an ExtractionConfiguration, as generated by an Extracion To DB pipeline is ready for Release. 
    /// This includes making sure that the current configuration in the database matches the extracted tables that are destined for release.
    /// </summary>
    public class MsSqlExtractionReleasePotential : ReleasePotential
    {
        public MsSqlExtractionReleasePotential(IRDMPPlatformRepositoryServiceLocator repositoryLocator, ISelectedDataSets selectedDataSets): base(repositoryLocator, selectedDataSets)
        {
        }

        protected override Releaseability GetSupplementalSpecificAssessment(ISupplementalExtractionResults supplementalExtractionResults)
        {
            return Releaseability.Undefined;
        }

        protected override Releaseability GetSpecificAssessment(ICumulativeExtractionResults extractionResults)
        {
            var _extractDir = Configuration.GetProject().ExtractionDirectory;

            ExtractDirectory = new ExtractionDirectory(_extractDir, Configuration).GetDirectoryForDataset(DataSet);

            var externalServerId = int.Parse(extractionResults.DestinationDescription.Split('|')[0]);
            var externalServer = _repositoryLocator.CatalogueRepository.GetObjectByID<ExternalDatabaseServer>(externalServerId);
            var dbName = extractionResults.DestinationDescription.Split('|')[1];
            var tblName = extractionResults.DestinationDescription.Split('|')[2];
            var server = DataAccessPortal.GetInstance().ExpectServer(externalServer, DataAccessContext.DataExport, setInitialDatabase: false);
            var database = server.ExpectDatabase(dbName);
            if (!database.Exists())
            {
                return Releaseability.ExtractFilesMissing;
            }
            var foundTable = database.ExpectTable(tblName);
            if (!foundTable.Exists())
            {
                return Releaseability.ExtractFilesMissing;
            }
            
            return Releaseability.Undefined;
        }
    }
}