//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rdmp.Core.Icons.IconOverlays {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Overlays {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Overlays() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rdmp.Core.Icons.IconOverlays.Overlays", typeof(Overlays).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type SixLabors.ImageSharp.Image.
        /// </summary>
        internal static SixLabors.ImageSharp.Image Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((SixLabors.ImageSharp.Image)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type SixLabors.ImageSharp.Image.
        /// </summary>
        internal static SixLabors.ImageSharp.Image Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((SixLabors.ImageSharp.Image)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type SixLabors.ImageSharp.Image.
        /// </summary>
        internal static SixLabors.ImageSharp.Image Deprecated {
            get {
                object obj = ResourceManager.GetObject("Deprecated", resourceCulture);
                return ((SixLabors.ImageSharp.Image)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type SixLabors.ImageSharp.Image.
        /// </summary>
        internal static SixLabors.ImageSharp.Image Edit {
            get {
                object obj = ResourceManager.GetObject("Edit", resourceCulture);
                return ((SixLabors.ImageSharp.Image)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type SixLabors.ImageSharp.Image.
        /// </summary>
        internal static SixLabors.ImageSharp.Image Execute {
            get {
                object obj = ResourceManager.GetObject("Execute", resourceCulture);
                return ((SixLabors.ImageSharp.Image)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type SixLabors.ImageSharp.Image.
        /// </summary>
        internal static SixLabors.ImageSharp.Image Extractable {
            get {
                object obj = ResourceManager.GetObject("Extractable", resourceCulture);
                return ((SixLabors.ImageSharp.Image)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type SixLabors.ImageSharp.Image.
        /// </summary>
        internal static SixLabors.ImageSharp.Image Extractable_Internal {
            get {
                object obj = ResourceManager.GetObject("Extractable_Internal", resourceCulture);
                return ((SixLabors.ImageSharp.Image)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type SixLabors.ImageSharp.Image.
        /// </summary>
        internal static SixLabors.ImageSharp.Image Extractable_SpecialApproval {
            get {
                object obj = ResourceManager.GetObject("Extractable_SpecialApproval", resourceCulture);
                return ((SixLabors.ImageSharp.Image)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type SixLabors.ImageSharp.Image.
        /// </summary>
        internal static SixLabors.ImageSharp.Image Extractable_Supplemental {
            get {
                object obj = ResourceManager.GetObject("Extractable_Supplemental", resourceCulture);
                return ((SixLabors.ImageSharp.Image)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type SixLabors.ImageSharp.Image.
        /// </summary>
        internal static SixLabors.ImageSharp.Image FavouredItem {
            get {
                object obj = ResourceManager.GetObject("FavouredItem", resourceCulture);
                return ((SixLabors.ImageSharp.Image)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type SixLabors.ImageSharp.Image.
        /// </summary>
        internal static SixLabors.ImageSharp.Image Filter {
            get {
                object obj = ResourceManager.GetObject("Filter", resourceCulture);
                return ((SixLabors.ImageSharp.Image)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type SixLabors.ImageSharp.Image.
        /// </summary>
        internal static SixLabors.ImageSharp.Image Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((SixLabors.ImageSharp.Image)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type SixLabors.ImageSharp.Image.
        /// </summary>
        internal static SixLabors.ImageSharp.Image Import {
            get {
                object obj = ResourceManager.GetObject("Import", resourceCulture);
                return ((SixLabors.ImageSharp.Image)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type SixLabors.ImageSharp.Image.
        /// </summary>
        internal static SixLabors.ImageSharp.Image Internal {
            get {
                object obj = ResourceManager.GetObject("Internal", resourceCulture);
                return ((SixLabors.ImageSharp.Image)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type SixLabors.ImageSharp.Image.
        /// </summary>
        internal static SixLabors.ImageSharp.Image Key {
            get {
                object obj = ResourceManager.GetObject("Key", resourceCulture);
                return ((SixLabors.ImageSharp.Image)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type SixLabors.ImageSharp.Image.
        /// </summary>
        internal static SixLabors.ImageSharp.Image IsExtractionIdentifier
        {
            get
            {
                object obj = ResourceManager.GetObject("IsExtractionIdentifier", resourceCulture);
                return ((SixLabors.ImageSharp.Image)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type SixLabors.ImageSharp.Image.
        /// </summary>
        internal static SixLabors.ImageSharp.Image Link {
            get {
                object obj = ResourceManager.GetObject("Link", resourceCulture);
                return ((SixLabors.ImageSharp.Image)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type SixLabors.ImageSharp.Image.
        /// </summary>
        internal static SixLabors.ImageSharp.Image Locked {
            get {
                object obj = ResourceManager.GetObject("Locked", resourceCulture);
                return ((SixLabors.ImageSharp.Image)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type SixLabors.ImageSharp.Image.
        /// </summary>
        internal static SixLabors.ImageSharp.Image None {
            get {
                object obj = ResourceManager.GetObject("None", resourceCulture);
                return ((SixLabors.ImageSharp.Image)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type SixLabors.ImageSharp.Image.
        /// </summary>
        internal static SixLabors.ImageSharp.Image Problem {
            get {
                object obj = ResourceManager.GetObject("Problem", resourceCulture);
                return ((SixLabors.ImageSharp.Image)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type SixLabors.ImageSharp.Image.
        /// </summary>
        internal static SixLabors.ImageSharp.Image Shortcut {
            get {
                object obj = ResourceManager.GetObject("Shortcut", resourceCulture);
                return ((SixLabors.ImageSharp.Image)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type SixLabors.ImageSharp.Image.
        /// </summary>
        internal static SixLabors.ImageSharp.Image Hashed {
            get {
                object obj = ResourceManager.GetObject("Hashed", resourceCulture);
                return ((SixLabors.ImageSharp.Image)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type SixLabors.ImageSharp.Image.
        /// </summary>
        internal static SixLabors.ImageSharp.Image BigE
        {
            get
            {
                object obj = ResourceManager.GetObject("BigE", resourceCulture);
                return ((SixLabors.ImageSharp.Image)(obj));
            }
        }
    }
}
