//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rdmp.Core.CommandLine.Gui {
    using System;
    using Terminal.Gui;
    
    
    public partial class ConsoleGuiServerDatabaseTableSelector : Terminal.Gui.Dialog {
        
        private Terminal.Gui.Label lblDescription;
        
        private Terminal.Gui.Label label1;
        
        private Terminal.Gui.Label lblUsername;
        
        private Terminal.Gui.TextField tbUsername;
        
        private Terminal.Gui.Label lblPassword;
        
        private Terminal.Gui.TextField tbPassword;
        
        private Terminal.Gui.Button btnUseExisting;
        
        private Terminal.Gui.Label lblServer;
        
        private Terminal.Gui.TextField tbServer;
        
        private Terminal.Gui.Label label4;
        
        private Terminal.Gui.ComboBox cbxDatabaseType;
        
        private Terminal.Gui.Label lblDatabase;
        
        private Terminal.Gui.TextField tbDatabase;
        
        private Terminal.Gui.Button btnListDatabases;
        
        private Terminal.Gui.Button btnCreateDatabase;
        
        private Terminal.Gui.Label lblTable;
        
        private Terminal.Gui.TextField tbTable;
        
        private Terminal.Gui.Button btnListTables;
        
        private Terminal.Gui.Label lblSchema;
        
        private Terminal.Gui.TextField tbSchema;
        
        private Terminal.Gui.RadioGroup rgTableType;
        
        private Terminal.Gui.Button btnOk;
        
        private Terminal.Gui.Button btnCancel;
        
        private void InitializeComponent() {
            this.Width = 80;
            this.Height = 17;
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Text = "";
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.Blue;
            this.Border.Effect3D = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Select Database";
            this.lblDescription = new Terminal.Gui.Label();
            this.lblDescription.Width = 14;
            this.lblDescription.Height = 1;
            this.lblDescription.X = 0;
            this.lblDescription.Y = 0;
            this.lblDescription.Data = "lblDescription";
            this.lblDescription.Text = "lblDescription";
            this.lblDescription.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblDescription);
            this.label1 = new Terminal.Gui.Label();
            this.label1.Width = 22;
            this.label1.Height = 1;
            this.label1.X = 27;
            this.label1.Y = 1;
            this.label1.Data = "label1";
            this.label1.Text = "Credentials (Optional)";
            this.label1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label1);
            this.lblUsername = new Terminal.Gui.Label();
            this.lblUsername.Width = 7;
            this.lblUsername.Height = 1;
            this.lblUsername.X = 3;
            this.lblUsername.Y = 2;
            this.lblUsername.Data = "lblUsername";
            this.lblUsername.Text = "UserID:";
            this.lblUsername.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblUsername);
            this.tbUsername = new Terminal.Gui.TextField();
            this.tbUsername.Width = Dim.Fill(20);
            this.tbUsername.Height = 1;
            this.tbUsername.X = 11;
            this.tbUsername.Y = 2;
            this.tbUsername.Data = "tbUsername";
            this.tbUsername.Text = "";
            this.tbUsername.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.tbUsername);
            this.lblPassword = new Terminal.Gui.Label();
            this.lblPassword.Width = 9;
            this.lblPassword.Height = 1;
            this.lblPassword.X = 1;
            this.lblPassword.Y = 3;
            this.lblPassword.Data = "lblPassword";
            this.lblPassword.Text = "Password:";
            this.lblPassword.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblPassword);
            this.tbPassword = new Terminal.Gui.TextField();
            this.tbPassword.Width = Dim.Fill(20);
            this.tbPassword.Height = 1;
            this.tbPassword.X = 11;
            this.tbPassword.Y = 3;
            this.tbPassword.Data = "tbPassword";
            this.tbPassword.Text = "";
            this.tbPassword.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.tbPassword);
            this.btnUseExisting = new Terminal.Gui.Button();
            this.btnUseExisting.Width = 28;
            this.btnUseExisting.Height = 1;
            this.btnUseExisting.X = 22;
            this.btnUseExisting.Y = 4;
            this.btnUseExisting.Data = "btnUseExisting";
            this.btnUseExisting.Text = "Use Existing Credentials";
            this.btnUseExisting.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnUseExisting.IsDefault = false;
            this.Add(this.btnUseExisting);
            this.lblServer = new Terminal.Gui.Label();
            this.lblServer.Width = 7;
            this.lblServer.Height = 1;
            this.lblServer.X = 2;
            this.lblServer.Y = 6;
            this.lblServer.Data = "lblServer";
            this.lblServer.Text = "Server:";
            this.lblServer.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblServer);
            this.tbServer = new Terminal.Gui.TextField();
            this.tbServer.Width = 32;
            this.tbServer.Height = 1;
            this.tbServer.X = 11;
            this.tbServer.Y = 6;
            this.tbServer.Data = "tbServer";
            this.tbServer.Text = "";
            this.tbServer.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.tbServer);
            this.label4 = new Terminal.Gui.Label();
            this.label4.Width = 5;
            this.label4.Height = 1;
            this.label4.X = 47;
            this.label4.Y = 6;
            this.label4.Data = "label4";
            this.label4.Text = "Type:";
            this.label4.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label4);
            this.cbxDatabaseType = new Terminal.Gui.ComboBox();
            this.cbxDatabaseType.Width = 20;
            this.cbxDatabaseType.Height = 6;
            this.cbxDatabaseType.X = 53;
            this.cbxDatabaseType.Y = 6;
            this.cbxDatabaseType.Data = "cbxDatabaseType";
            this.cbxDatabaseType.Text = "";
            this.cbxDatabaseType.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.cbxDatabaseType);
            this.lblDatabase = new Terminal.Gui.Label();
            this.lblDatabase.Width = 9;
            this.lblDatabase.Height = 1;
            this.lblDatabase.X = 0;
            this.lblDatabase.Y = 8;
            this.lblDatabase.Data = "lblDatabase";
            this.lblDatabase.Text = "Database:";
            this.lblDatabase.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblDatabase);
            this.tbDatabase = new Terminal.Gui.TextField();
            this.tbDatabase.Width = 32;
            this.tbDatabase.Height = 1;
            this.tbDatabase.X = 11;
            this.tbDatabase.Y = 8;
            this.tbDatabase.Data = "tbDatabase";
            this.tbDatabase.Text = "";
            this.tbDatabase.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.tbDatabase);
            this.btnListDatabases = new Terminal.Gui.Button();
            this.btnListDatabases.Width = 18;
            this.btnListDatabases.Height = 1;
            this.btnListDatabases.X = 44;
            this.btnListDatabases.Y = 8;
            this.btnListDatabases.Data = "btnListDatabases";
            this.btnListDatabases.Text = "List Databases";
            this.btnListDatabases.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnListDatabases.IsDefault = false;
            this.Add(this.btnListDatabases);
            this.btnCreateDatabase = new Terminal.Gui.Button();
            this.btnCreateDatabase.Width = 19;
            this.btnCreateDatabase.Height = 1;
            this.btnCreateDatabase.X = 44;
            this.btnCreateDatabase.Y = 9;
            this.btnCreateDatabase.Data = "btnCreateDatabase";
            this.btnCreateDatabase.Text = "Create Database";
            this.btnCreateDatabase.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnCreateDatabase.IsDefault = false;
            this.Add(this.btnCreateDatabase);
            this.lblTable = new Terminal.Gui.Label();
            this.lblTable.Width = 6;
            this.lblTable.Height = 1;
            this.lblTable.X = 3;
            this.lblTable.Y = 10;
            this.lblTable.Data = "lblTable";
            this.lblTable.Text = "Table:";
            this.lblTable.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblTable);
            this.tbTable = new Terminal.Gui.TextField();
            this.tbTable.Width = 32;
            this.tbTable.Height = 1;
            this.tbTable.X = 11;
            this.tbTable.Y = Pos.Top(lblTable);
            this.tbTable.Data = "tbTable";
            this.tbTable.Text = "";
            this.tbTable.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.tbTable);
            this.btnListTables = new Terminal.Gui.Button();
            this.btnListTables.Width = 15;
            this.btnListTables.Height = 1;
            this.btnListTables.X = 44;
            this.btnListTables.Y = 10;
            this.btnListTables.Data = "btnListTables";
            this.btnListTables.Text = "List Tables";
            this.btnListTables.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnListTables.IsDefault = false;
            this.Add(this.btnListTables);
            this.lblSchema = new Terminal.Gui.Label();
            this.lblSchema.Width = 7;
            this.lblSchema.Height = 1;
            this.lblSchema.X = 2;
            this.lblSchema.Y = 12;
            this.lblSchema.Data = "lblSchema";
            this.lblSchema.Text = "Schema:";
            this.lblSchema.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblSchema);
            this.tbSchema = new Terminal.Gui.TextField();
            this.tbSchema.Width = 32;
            this.tbSchema.Height = 1;
            this.tbSchema.X = 11;
            this.tbSchema.Y = 12;
            this.tbSchema.Data = "tbSchema";
            this.tbSchema.Text = "";
            this.tbSchema.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.tbSchema);
            this.rgTableType = new Terminal.Gui.RadioGroup();
            this.rgTableType.Width = 24;
            this.rgTableType.Height = 3;
            this.rgTableType.X = 44;
            this.rgTableType.Y = 12;
            this.rgTableType.Data = "rgTableType";
            this.rgTableType.Text = "";
            this.rgTableType.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.rgTableType.RadioLabels = new NStack.ustring[] {
                    "Regular Table",
                    "View",
                    "Table Valued Function"};
            this.Add(this.rgTableType);
            this.btnOk = new Terminal.Gui.Button();
            this.btnOk.Width = 8;
            this.btnOk.Height = 1;
            this.btnOk.X = 1;
            this.btnOk.Y = 14;
            this.btnOk.Data = "btnOk";
            this.btnOk.Text = "Ok";
            this.btnOk.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnOk.IsDefault = true;
            this.Add(this.btnOk);
            this.btnCancel = new Terminal.Gui.Button();
            this.btnCancel.Width = 11;
            this.btnCancel.Height = 1;
            this.btnCancel.X = 11;
            this.btnCancel.Y = 14;
            this.btnCancel.Data = "btnCancel";
            this.btnCancel.Text = "C_ancel";
            this.btnCancel.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnCancel.IsDefault = false;
            this.Add(this.btnCancel);
        }
    }
}
