
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.9.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Rdmp.Core.CommandLine.Gui {
    using System;
    using Terminal.Gui;
    
    
    public partial class ConsoleGuiCohortIdentificationConfigurationUI : Terminal.Gui.Window {
        
        private Terminal.Gui.Button btnRun;
        
        private Terminal.Gui.Button btnAbort;
        
        private Terminal.Gui.Button btnClearCache;
        
        private Terminal.Gui.Button btnCommitCohort;
        
        private Terminal.Gui.Label lblState;
        
        private Terminal.Gui.Button btnClose;
        
        private Terminal.Gui.CheckBox cbCumulativeTotals;
        
        private Terminal.Gui.TableView tableview1;
        
        private void InitializeComponent() {
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = false;
            this.Text = "";
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.Blue;
            this.Border.Effect3D = false;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = null;
            this.btnRun = new Terminal.Gui.Button();
            this.btnRun.Width = 7;
            this.btnRun.Height = 1;
            this.btnRun.X = 0;
            this.btnRun.Y = 0;
            this.btnRun.Data = "btnRun";
            this.btnRun.Text = "Run";
            this.btnRun.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnRun.IsDefault = false;
            this.Add(this.btnRun);
            this.btnAbort = new Terminal.Gui.Button();
            this.btnAbort.Width = 9;
            this.btnAbort.Height = 1;
            this.btnAbort.X = 8;
            this.btnAbort.Y = 0;
            this.btnAbort.Data = "btnAbort";
            this.btnAbort.Text = "Abort";
            this.btnAbort.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnAbort.IsDefault = false;
            this.Add(this.btnAbort);
            this.btnClearCache = new Terminal.Gui.Button();
            this.btnClearCache.Width = 15;
            this.btnClearCache.Height = 1;
            this.btnClearCache.X = 18;
            this.btnClearCache.Y = 0;
            this.btnClearCache.Data = "btnClearCache";
            this.btnClearCache.Text = "Clear Cache";
            this.btnClearCache.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnClearCache.IsDefault = false;
            this.Add(this.btnClearCache);
            this.btnCommitCohort = new Terminal.Gui.Button();
            this.btnCommitCohort.Width = 18;
            this.btnCommitCohort.Height = 1;
            this.btnCommitCohort.X = 37;
            this.btnCommitCohort.Y = 0;
            this.btnCommitCohort.Data = "btnCommitCohort";
            this.btnCommitCohort.Text = "Co_mmit Cohort";
            this.btnCommitCohort.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnCommitCohort.IsDefault = false;
            this.Add(this.btnCommitCohort);
            this.lblState = new Terminal.Gui.Label();
            this.lblState.Width = 6;
            this.lblState.Height = 1;
            this.lblState.X = 0;
            this.lblState.Y = 1;
            this.lblState.Data = "lblState";
            this.lblState.Text = "State:";
            this.lblState.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblState);
            this.btnClose = new Terminal.Gui.Button();
            this.btnClose.Width = 10;
            this.btnClose.Height = 1;
            this.btnClose.X = 37;
            this.btnClose.Y = 1;
            this.btnClose.Data = "btnClose";
            this.btnClose.Text = "Clos_e";
            this.btnClose.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnClose.IsDefault = false;
            this.Add(this.btnClose);
            this.cbCumulativeTotals = new Terminal.Gui.CheckBox();
            this.cbCumulativeTotals.Width = 4;
            this.cbCumulativeTotals.Height = 1;
            this.cbCumulativeTotals.X = 55;
            this.cbCumulativeTotals.Y = 1;
            this.cbCumulativeTotals.Data = "cbCumulativeTotals";
            this.cbCumulativeTotals.Text = "Cumulative Totals";
            this.cbCumulativeTotals.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.cbCumulativeTotals.Checked = false;
            this.Add(this.cbCumulativeTotals);
            this.tableview1 = new Terminal.Gui.TableView();
            this.tableview1.Width = Dim.Fill(0);
            this.tableview1.Height = Dim.Fill(0);
            this.tableview1.X = 0;
            this.tableview1.Y = 2;
            this.tableview1.Data = "tableview1";
            this.tableview1.Text = "";
            this.tableview1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.tableview1.Style.AlwaysShowHeaders = false;
            this.tableview1.Style.ExpandLastColumn = true;
            this.tableview1.Style.InvertSelectedCellFirstCharacter = false;
            this.tableview1.Style.ShowHorizontalHeaderOverline = true;
            this.tableview1.Style.ShowHorizontalHeaderUnderline = true;
            this.tableview1.Style.ShowVerticalCellLines = true;
            this.tableview1.Style.ShowVerticalHeaderLines = true;
            System.Data.DataTable tableview1Table;
            tableview1Table = new System.Data.DataTable();
            System.Data.DataColumn tableview1TableName;
            tableview1TableName = new System.Data.DataColumn();
            tableview1TableName.ColumnName = "Name";
            tableview1Table.Columns.Add(tableview1TableName);
            System.Data.DataColumn tableview1TableExecute;
            tableview1TableExecute = new System.Data.DataColumn();
            tableview1TableExecute.ColumnName = "Execute";
            tableview1Table.Columns.Add(tableview1TableExecute);
            System.Data.DataColumn tableview1TableCached;
            tableview1TableCached = new System.Data.DataColumn();
            tableview1TableCached.ColumnName = "Cached";
            tableview1Table.Columns.Add(tableview1TableCached);
            System.Data.DataColumn tableview1TableCumulativeTotal;
            tableview1TableCumulativeTotal = new System.Data.DataColumn();
            tableview1TableCumulativeTotal.ColumnName = "CumulativeTotal";
            tableview1Table.Columns.Add(tableview1TableCumulativeTotal);
            System.Data.DataColumn tableview1TableCount;
            tableview1TableCount = new System.Data.DataColumn();
            tableview1TableCount.ColumnName = "Count";
            tableview1Table.Columns.Add(tableview1TableCount);
            System.Data.DataColumn tableview1TableWorking;
            tableview1TableWorking = new System.Data.DataColumn();
            tableview1TableWorking.ColumnName = "Working";
            tableview1Table.Columns.Add(tableview1TableWorking);
            System.Data.DataColumn tableview1TableTime;
            tableview1TableTime = new System.Data.DataColumn();
            tableview1TableTime.ColumnName = "Time";
            tableview1Table.Columns.Add(tableview1TableTime);
            System.Data.DataColumn tableview1TableCatalogue;
            tableview1TableCatalogue = new System.Data.DataColumn();
            tableview1TableCatalogue.ColumnName = "Catalogue";
            tableview1Table.Columns.Add(tableview1TableCatalogue);
            System.Data.DataColumn tableview1TableID;
            tableview1TableID = new System.Data.DataColumn();
            tableview1TableID.ColumnName = "ID";
            tableview1Table.Columns.Add(tableview1TableID);
            this.tableview1.Table = tableview1Table;
            this.Add(this.tableview1);
        }
    }
}
