//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rdmp.Core.CommandLine.Gui {
    using System;
    using Terminal.Gui;
    
    
    public partial class ConsoleGuiServerDatabaseTableSelector : Terminal.Gui.Dialog {
        
        private Terminal.Gui.Label lblDescription;
        
        private Terminal.Gui.FrameView frameview1;
        
        private Terminal.Gui.Label lblUsername;
        
        private Terminal.Gui.TextField tbUsername;
        
        private Terminal.Gui.Label lblPassword;
        
        private Terminal.Gui.TextField tbPassword;
        
        private Terminal.Gui.Button btnUseExisting;
        
        private Terminal.Gui.Label label1;
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.ComboBox cbxServer;
        
        private Terminal.Gui.Label label4;
        
        private Terminal.Gui.ComboBox cbxDatabaseType;
        
        private Terminal.Gui.Label label3;
        
        private Terminal.Gui.ComboBox cbxDatabase;
        
        private Terminal.Gui.Button btnRefresh;
        
        private Terminal.Gui.Button btnCreateDatabase;
        
        private Terminal.Gui.Label lblTable;
        
        private Terminal.Gui.ComboBox cbxTable;
        
        private Terminal.Gui.RadioGroup rgTableType;
        
        private Terminal.Gui.Label lblSchema;
        
        private Terminal.Gui.TextField tbSchema;
        
        private Terminal.Gui.Button btnOk;
        
        private Terminal.Gui.Button btnCancel;
        
        private void InitializeComponent() {
            this.Width = 80;
            this.Height = 25;
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Text = "";
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.Blue;
            this.Border.Effect3D = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Select Database";
            this.lblDescription = new Terminal.Gui.Label();
            this.lblDescription.Width = 14;
            this.lblDescription.Height = 1;
            this.lblDescription.X = 0;
            this.lblDescription.Y = 0;
            this.lblDescription.Data = "lblDescription";
            this.lblDescription.Text = "lblDescription";
            this.lblDescription.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblDescription);
            this.frameview1 = new Terminal.Gui.FrameView();
            this.frameview1.Width = 50;
            this.frameview1.Height = 5;
            this.frameview1.X = 1;
            this.frameview1.Y = 4;
            this.frameview1.Data = "frameview1";
            this.frameview1.Text = "H";
            this.frameview1.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.frameview1.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.frameview1.Border.Effect3D = false;
            this.frameview1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.frameview1);
            this.lblUsername = new Terminal.Gui.Label();
            this.lblUsername.Width = 7;
            this.lblUsername.Height = 1;
            this.lblUsername.X = 0;
            this.lblUsername.Y = 0;
            this.lblUsername.Data = "lblUsername";
            this.lblUsername.Text = "UserID:";
            this.lblUsername.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameview1.Add(this.lblUsername);
            this.tbUsername = new Terminal.Gui.TextField();
            this.tbUsername.Width = Dim.Fill(0);
            this.tbUsername.Height = 1;
            this.tbUsername.X = 10;
            this.tbUsername.Y = 0;
            this.tbUsername.Data = "tbUsername";
            this.tbUsername.Text = "";
            this.tbUsername.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameview1.Add(this.tbUsername);
            this.lblPassword = new Terminal.Gui.Label();
            this.lblPassword.Width = 8;
            this.lblPassword.Height = 1;
            this.lblPassword.X = 0;
            this.lblPassword.Y = 1;
            this.lblPassword.Data = "lblPassword";
            this.lblPassword.Text = "Password";
            this.lblPassword.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameview1.Add(this.lblPassword);
            this.tbPassword = new Terminal.Gui.TextField();
            this.tbPassword.Width = Dim.Fill(0);
            this.tbPassword.Height = 1;
            this.tbPassword.X = 10;
            this.tbPassword.Y = 1;
            this.tbPassword.Data = "tbPassword";
            this.tbPassword.Text = "";
            this.tbPassword.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameview1.Add(this.tbPassword);
            this.btnUseExisting = new Terminal.Gui.Button();
            this.btnUseExisting.Width = 16;
            this.btnUseExisting.Height = 1;
            this.btnUseExisting.X = 32;
            this.btnUseExisting.Y = 2;
            this.btnUseExisting.Data = "btnUseExisting";
            this.btnUseExisting.Text = "Use Existing";
            this.btnUseExisting.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnUseExisting.IsDefault = false;
            this.frameview1.Add(this.btnUseExisting);
            this.label1 = new Terminal.Gui.Label();
            this.label1.Width = 22;
            this.label1.Height = 1;
            this.label1.X = 2;
            this.label1.Y = 4;
            this.label1.Data = "label1";
            this.label1.Text = "Credentials (Optional)";
            this.label1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label1);
            this.label2 = new Terminal.Gui.Label();
            this.label2.Width = 7;
            this.label2.Height = 1;
            this.label2.X = 1;
            this.label2.Y = 10;
            this.label2.Data = "label2";
            this.label2.Text = "Server:";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label2);
            this.cbxServer = new Terminal.Gui.ComboBox();
            this.cbxServer.Width = 32;
            this.cbxServer.Height = 5;
            this.cbxServer.X = 11;
            this.cbxServer.Y = 10;
            this.cbxServer.Data = "tbServer";
            this.cbxServer.Text = "";
            this.cbxServer.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.cbxServer);
            this.label4 = new Terminal.Gui.Label();
            this.label4.Width = 5;
            this.label4.Height = 1;
            this.label4.X = 47;
            this.label4.Y = 10;
            this.label4.Data = "label4";
            this.label4.Text = "Type:";
            this.label4.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label4);
            this.cbxDatabaseType = new Terminal.Gui.ComboBox();
            this.cbxDatabaseType.Width = 20;
            this.cbxDatabaseType.Height = 6;
            this.cbxDatabaseType.X = 53;
            this.cbxDatabaseType.Y = 10;
            this.cbxDatabaseType.Data = "cbxDatabaseType";
            this.cbxDatabaseType.Text = "";
            this.cbxDatabaseType.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.cbxDatabaseType);
            this.label3 = new Terminal.Gui.Label();
            this.label3.Width = 9;
            this.label3.Height = 1;
            this.label3.X = 1;
            this.label3.Y = 13;
            this.label3.Data = "label3";
            this.label3.Text = "Database:";
            this.label3.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label3);
            this.cbxDatabase = new Terminal.Gui.ComboBox();
            this.cbxDatabase.Width = 32;
            this.cbxDatabase.Height = 5;
            this.cbxDatabase.X = 11;
            this.cbxDatabase.Y = 13;
            this.cbxDatabase.Data = "tbDatabase";
            this.cbxDatabase.Text = "";
            this.cbxDatabase.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.cbxDatabase);
            this.btnRefresh = new Terminal.Gui.Button();
            this.btnRefresh.Width = 11;
            this.btnRefresh.Height = 1;
            this.btnRefresh.X = 46;
            this.btnRefresh.Y = 13;
            this.btnRefresh.Data = "btnRefresh";
            this.btnRefresh.Text = "Refresh";
            this.btnRefresh.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnRefresh.IsDefault = false;
            this.Add(this.btnRefresh);
            this.btnCreateDatabase = new Terminal.Gui.Button();
            this.btnCreateDatabase.Width = 19;
            this.btnCreateDatabase.Height = 1;
            this.btnCreateDatabase.X = 46;
            this.btnCreateDatabase.Y = 14;
            this.btnCreateDatabase.Data = "btnCreateDatabase";
            this.btnCreateDatabase.Text = "Create Database";
            this.btnCreateDatabase.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnCreateDatabase.IsDefault = false;
            this.Add(this.btnCreateDatabase);
            this.lblTable = new Terminal.Gui.Label();
            this.lblTable.Width = 6;
            this.lblTable.Height = 1;
            this.lblTable.X = 1;
            this.lblTable.Y = 16;
            this.lblTable.Data = "lblTable";
            this.lblTable.Text = "Table:";
            this.lblTable.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblTable);
            this.cbxTable = new Terminal.Gui.ComboBox();
            this.cbxTable.Width = 32;
            this.cbxTable.Height = 5;
            this.cbxTable.X = 11;
            this.cbxTable.Y = 16;
            this.cbxTable.Data = "tbTable";
            this.cbxTable.Text = "";
            this.cbxTable.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.cbxTable);
            this.rgTableType = new Terminal.Gui.RadioGroup();
            this.rgTableType.Width = 24;
            this.rgTableType.Height = 3;
            this.rgTableType.X = 46;
            this.rgTableType.Y = 16;
            this.rgTableType.Data = "rgTableType";
            this.rgTableType.Text = "";
            this.rgTableType.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.rgTableType.RadioLabels = new NStack.ustring[] {
                    "Regular Table",
                    "View",
                    "Table Valued Function"};
            this.Add(this.rgTableType);
            this.lblSchema = new Terminal.Gui.Label();
            this.lblSchema.Width = 7;
            this.lblSchema.Height = 1;
            this.lblSchema.X = 1;
            this.lblSchema.Y = 19;
            this.lblSchema.Data = "lblSchema";
            this.lblSchema.Text = "Schema:";
            this.lblSchema.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblSchema);
            this.tbSchema = new Terminal.Gui.TextField();
            this.tbSchema.Width = 32;
            this.tbSchema.Height = 1;
            this.tbSchema.X = 11;
            this.tbSchema.Y = 19;
            this.tbSchema.Data = "tbSchema";
            this.tbSchema.Text = "";
            this.tbSchema.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.tbSchema);
            this.btnOk = new Terminal.Gui.Button();
            this.btnOk.Width = 8;
            this.btnOk.Height = 1;
            this.btnOk.X = 1;
            this.btnOk.Y = 21;
            this.btnOk.Data = "btnOk";
            this.btnOk.Text = "Ok";
            this.btnOk.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnOk.IsDefault = true;
            this.Add(this.btnOk);
            this.btnCancel = new Terminal.Gui.Button();
            this.btnCancel.Width = 11;
            this.btnCancel.Height = 1;
            this.btnCancel.X = 10;
            this.btnCancel.Y = 21;
            this.btnCancel.Data = "btnCancel";
            this.btnCancel.Text = "C_ancel";
            this.btnCancel.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnCancel.IsDefault = false;
            this.Add(this.btnCancel);
        }
    }
}
