using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace CatalogueLibrary.Data.Dashboarding
{
    /// <summary>
    /// Helps you create simple string based argument lists
    /// </summary>
    public class PersistStringHelper
    {
        /// <summary>
        /// Serializes the dictionary to a string of XML
        /// </summary>
        /// <param name="dict"></param>
        /// <returns></returns>
        public string SaveDictionaryToString(Dictionary<string, string> dict)
        {
            
            XElement el = new XElement("root",
                dict.Select(kv => new XElement(kv.Key, kv.Value)));

            return el.ToString();
        }

        /// <summary>
        /// Creates a dictionary by deserializing the XML string provided (e.g. a string generated by <see cref="SaveDictionaryToString"/>) 
        /// </summary>
        /// <param name="str"></param>
        /// <returns></returns>
        public Dictionary<string, string> LoadDictionaryFromString(string str)
        {
            if(string.IsNullOrWhiteSpace(str))
                return new Dictionary<string, string>();

            XElement rootElement = XElement.Parse(str);
            Dictionary<string, string> dict = new Dictionary<string, string>();
            foreach (var el in rootElement.Elements())
                dict.Add(el.Name.LocalName, el.Value);

            return dict;
        }

        /// <summary>
        /// Fetches the given key from the serialized <paramref name="persistString"/> (e.g. a string generated by <see cref="SaveDictionaryToString"/>) 
        /// 
        /// <para>If you need lots of values you should probably just use <see cref="LoadDictionaryFromString"/> instead</para>
        /// </summary>
        /// <param name="key"></param>
        /// <param name="persistString"></param>
        /// <returns></returns>
        public string GetValueIfExistsFromPersistString(string key, string persistString)
        {
            var dict = LoadDictionaryFromString(persistString);

            if(dict.ContainsKey(key))
                return dict[key];
            
            return null;
        }
    }
}
