//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;

namespace Rdmp.Core.Icons.IconProvision
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CatalogueIcons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CatalogueIcons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rdmp.Core.Icons.IconProvision.CatalogueIcons", typeof(CatalogueIcons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AggregateContinuousDateAxis {
            get {
                object obj = ResourceManager.GetObject("AggregateContinuousDateAxis", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AggregateDimension {
            get {
                object obj = ResourceManager.GetObject("AggregateDimension", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AggregateGraph {
            get {
                object obj = ResourceManager.GetObject("AggregateGraph", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AggregatesNode {
            get {
                object obj = ResourceManager.GetObject("AggregatesNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AggregateTopX {
            get {
                object obj = ResourceManager.GetObject("AggregateTopX", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AllANOTablesNode {
            get {
                object obj = ResourceManager.GetObject("AllANOTablesNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AllAutomationServerSlotsNode {
            get {
                object obj = ResourceManager.GetObject("AllAutomationServerSlotsNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AllCataloguesUsedByLoadMetadataNode {
            get {
                object obj = ResourceManager.GetObject("AllCataloguesUsedByLoadMetadataNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AllCohortsNode {
            get {
                object obj = ResourceManager.GetObject("AllCohortsNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AllConnectionStringKeywordsNode {
            get {
                object obj = ResourceManager.GetObject("AllConnectionStringKeywordsNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AllDashboardsNode {
            get {
                object obj = ResourceManager.GetObject("AllDashboardsNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AllDataAccessCredentialsNode {
            get {
                object obj = ResourceManager.GetObject("AllDataAccessCredentialsNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AllExpiredPluginsNode {
            get {
                object obj = ResourceManager.GetObject("AllExpiredPluginsNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AllExternalServersNode {
            get {
                object obj = ResourceManager.GetObject("AllExternalServersNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AllFreeCohortIdentificationConfigurationsNode {
            get {
                object obj = ResourceManager.GetObject("AllFreeCohortIdentificationConfigurationsNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AllGovernanceNode {
            get {
                object obj = ResourceManager.GetObject("AllGovernanceNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AllLoadMetadatasNode {
            get {
                object obj = ResourceManager.GetObject("AllLoadMetadatasNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AllObjectExportsNode {
            get {
                object obj = ResourceManager.GetObject("AllObjectExportsNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AllObjectImportsNode {
            get {
                object obj = ResourceManager.GetObject("AllObjectImportsNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AllObjectSharingNode {
            get {
                object obj = ResourceManager.GetObject("AllObjectSharingNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AllOrphanAggregateConfigurationsNode {
            get {
                object obj = ResourceManager.GetObject("AllOrphanAggregateConfigurationsNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AllPermissionWindowsNode {
            get {
                object obj = ResourceManager.GetObject("AllPermissionWindowsNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AllTemplateAggregateConfigurationsNode
        {
            get {
                object obj = ResourceManager.GetObject("AllTemplateAggregateConfigurationsNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AllPipelinesNode {
            get {
                object obj = ResourceManager.GetObject("AllPipelinesNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AllPluginsNode {
            get {
                object obj = ResourceManager.GetObject("AllPluginsNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AllProcessTasksUsedByLoadMetadataNode {
            get {
                object obj = ResourceManager.GetObject("AllProcessTasksUsedByLoadMetadataNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AllProjectCohortIdentificationConfigurationsNode {
            get {
                object obj = ResourceManager.GetObject("AllProjectCohortIdentificationConfigurationsNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AllRDMPRemotesNode {
            get {
                object obj = ResourceManager.GetObject("AllRDMPRemotesNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AllServersNode {
            get {
                object obj = ResourceManager.GetObject("AllServersNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AllStandardRegexesNode {
            get {
                object obj = ResourceManager.GetObject("AllStandardRegexesNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ANOColumnInfo {
            get {
                object obj = ResourceManager.GetObject("ANOColumnInfo", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ANOTable {
            get {
                object obj = ResourceManager.GetObject("ANOTable", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AutomateablePipeline {
            get {
                object obj = ResourceManager.GetObject("AutomateablePipeline", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AutomationServiceException {
            get {
                object obj = ResourceManager.GetObject("AutomationServiceException", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> AutomationServiceSlot {
            get {
                object obj = ResourceManager.GetObject("AutomationServiceSlot", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Backup {
            get {
                object obj = ResourceManager.GetObject("Backup", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> BigCohort {
            get {
                object obj = ResourceManager.GetObject("BigCohort", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> BigGraph {
            get {
                object obj = ResourceManager.GetObject("BigGraph", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> BigPatientIndexTable {
            get {
                object obj = ResourceManager.GetObject("BigPatientIndexTable", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> CacheFetchFailure {
            get {
                object obj = ResourceManager.GetObject("CacheFetchFailure", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> CacheProgress {
            get {
                object obj = ResourceManager.GetObject("CacheProgress", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Catalogue {
            get {
                object obj = ResourceManager.GetObject("Catalogue", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> CatalogueFolder {
            get {
                object obj = ResourceManager.GetObject("CatalogueFolder", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> CatalogueItem {
            get {
                object obj = ResourceManager.GetObject("CatalogueItem", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> CatalogueItemTransform
        {
            get
            {
                object obj = ResourceManager.GetObject("CatalogueItemTransform", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> CatalogueItemIssue {
            get {
                object obj = ResourceManager.GetObject("CatalogueItemIssue", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> CatalogueItemsNode {
            get {
                object obj = ResourceManager.GetObject("CatalogueItemsNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> CatalogueLookupsNode {
            get {
                object obj = ResourceManager.GetObject("CatalogueLookupsNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Clipboard {
            get {
                object obj = ResourceManager.GetObject("Clipboard", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> CloneExtractionConfiguration {
            get {
                object obj = ResourceManager.GetObject("CloneExtractionConfiguration", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> CohortAggregate {
            get {
                object obj = ResourceManager.GetObject("CohortAggregate", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> CohortAggregateContainer {
            get {
                object obj = ResourceManager.GetObject("CohortAggregateContainer", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> CohortCustomColumn {
            get {
                object obj = ResourceManager.GetObject("CohortCustomColumn", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> CohortIdentificationConfiguration {
            get {
                object obj = ResourceManager.GetObject("CohortIdentificationConfiguration", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> collapseAllNodes {
            get {
                object obj = ResourceManager.GetObject("collapseAllNodes", resourceCulture);
                return (Image<Argb32>)obj;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> CollisionResolution {
            get {
                object obj = ResourceManager.GetObject("CollisionResolution", resourceCulture);
                return (Image<Argb32>)obj;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ColumnInfo {
            get {
                object obj = ResourceManager.GetObject("ColumnInfo", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ConnectionStringKeyword {
            get {
                object obj = ResourceManager.GetObject("ConnectionStringKeyword", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> CumulativeExtractionResults {
            get {
                object obj = ResourceManager.GetObject("CumulativeExtractionResults", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> DashboardControl {
            get {
                object obj = ResourceManager.GetObject("DashboardControl", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> DashboardLayout {
            get {
                object obj = ResourceManager.GetObject("DashboardLayout", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> DataAccessCredentials {
            get {
                object obj = ResourceManager.GetObject("DataAccessCredentials", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Database {
            get {
                object obj = ResourceManager.GetObject("Database", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> DatabaseRefresh {
            get {
                object obj = ResourceManager.GetObject("DatabaseRefresh", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> DecryptionPrivateKeyNode {
            get {
                object obj = ResourceManager.GetObject("DecryptionPrivateKeyNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Diff {
            get {
                object obj = ResourceManager.GetObject("Diff", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> DocumentationNode {
            get {
                object obj = ResourceManager.GetObject("DocumentationNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> DQE {
            get {
                object obj = ResourceManager.GetObject("DQE", resourceCulture);
                return (Image<Argb32>)obj;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> DQEGraphAnnotation {
            get {
                object obj = ResourceManager.GetObject("DQEGraphAnnotation", resourceCulture);
                return (Image<Argb32>)obj;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> DropHere {
            get {
                object obj = ResourceManager.GetObject("DropHere", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> EmptyProject {
            get {
                object obj = ResourceManager.GetObject("EmptyProject", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Evaluation {
            get {
                object obj = ResourceManager.GetObject("Evaluation", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> EXCEPT {
            get {
                object obj = ResourceManager.GetObject("EXCEPT", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> EXCEPTCohortAggregate {
            get {
                object obj = ResourceManager.GetObject("EXCEPTCohortAggregate", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Exe {
            get {
                object obj = ResourceManager.GetObject("Exe", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ExecuteArrow {
            get {
                object obj = ResourceManager.GetObject("ExecuteArrow", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ExecuteArrowWithTickOverlay {
            get {
                object obj = ResourceManager.GetObject("ExecuteArrowWithTickOverlay", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ExpandAllNodes {
            get {
                object obj = ResourceManager.GetObject("ExpandAllNodes", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static Image<Argb32> ExtendedProperty {
            get {
                object obj = ResourceManager.GetObject("ExtendedProperty", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ExternalCohortTable {
            get {
                object obj = ResourceManager.GetObject("ExternalCohortTable", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ExternalDatabaseServer {
            get {
                object obj = ResourceManager.GetObject("ExternalDatabaseServer", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ExternalDatabaseServer_ANO {
            get {
                object obj = ResourceManager.GetObject("ExternalDatabaseServer_ANO", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ExternalDatabaseServer_Cache {
            get {
                object obj = ResourceManager.GetObject("ExternalDatabaseServer_Cache", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ExternalDatabaseServer_DQE {
            get {
                object obj = ResourceManager.GetObject("ExternalDatabaseServer_DQE", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ExternalDatabaseServer_IdentifierDump {
            get {
                object obj = ResourceManager.GetObject("ExternalDatabaseServer_IdentifierDump", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ExternalDatabaseServer_Logging {
            get {
                object obj = ResourceManager.GetObject("ExternalDatabaseServer_Logging", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ExtractableCohort {
            get {
                object obj = ResourceManager.GetObject("ExtractableCohort", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ExtractableColumn {
            get {
                object obj = ResourceManager.GetObject("ExtractableColumn", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ExtractableDataSet {
            get {
                object obj = ResourceManager.GetObject("ExtractableDataSet", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ExtractableDataSetDisabled {
            get {
                object obj = ResourceManager.GetObject("ExtractableDataSetDisabled", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ExtractableDataSetPackage {
            get {
                object obj = ResourceManager.GetObject("ExtractableDataSetPackage", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ExtractableDataSetsNode {
            get {
                object obj = ResourceManager.GetObject("ExtractableDataSetsNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ExtractionConfiguration {
            get {
                object obj = ResourceManager.GetObject("ExtractionConfiguration", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ExtractionConfigurationsNode {
            get {
                object obj = ResourceManager.GetObject("ExtractionConfigurationsNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ExtractionDirectoryNode {
            get {
                object obj = ResourceManager.GetObject("ExtractionDirectoryNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ExtractionFilterParameterSet {
            get {
                object obj = ResourceManager.GetObject("ExtractionFilterParameterSet", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ExtractionInformation {
            get {
                object obj = ResourceManager.GetObject("ExtractionInformation", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ExtractionInformation_ProjectSpecific {
            get {
                object obj = ResourceManager.GetObject("ExtractionInformation_ProjectSpecific", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ExtractionInformation_SpecialApproval {
            get {
                object obj = ResourceManager.GetObject("ExtractionInformation_SpecialApproval", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ExtractionInformation_Supplemental {
            get {
                object obj = ResourceManager.GetObject("ExtractionInformation_Supplemental", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Failed {
            get {
                object obj = ResourceManager.GetObject("Failed", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Favourite {
            get {
                object obj = ResourceManager.GetObject("Favourite", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> File {
            get {
                object obj = ResourceManager.GetObject("File", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> FileMissing {
            get {
                object obj = ResourceManager.GetObject("FileMissing", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Filter {
            get {
                object obj = ResourceManager.GetObject("Filter", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> FilterContainer {
            get {
                object obj = ResourceManager.GetObject("FilterContainer", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> FrozenCohortIdentificationConfiguration {
            get {
                object obj = ResourceManager.GetObject("FrozenCohortIdentificationConfiguration", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> FrozenExtractionConfiguration {
            get {
                object obj = ResourceManager.GetObject("FrozenExtractionConfiguration", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> FrozenExtractionConfigurationsNode {
            get {
                object obj = ResourceManager.GetObject("FrozenExtractionConfigurationsNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> GetFilesStage {
            get {
                object obj = ResourceManager.GetObject("GetFilesStage", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> GovernanceDocument {
            get {
                object obj = ResourceManager.GetObject("GovernanceDocument", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> GovernancePeriod {
            get {
                object obj = ResourceManager.GetObject("GovernancePeriod", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Graph {
            get {
                object obj = ResourceManager.GetObject("Graph", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> GreenIssue {
            get {
                object obj = ResourceManager.GetObject("GreenIssue", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ImportFile {
            get {
                object obj = ResourceManager.GetObject("ImportFile", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> INTERSECT {
            get {
                object obj = ResourceManager.GetObject("INTERSECT", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> INTERSECTCohortAggregate {
            get {
                object obj = ResourceManager.GetObject("INTERSECTCohortAggregate", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> JoinableCollectionNode {
            get {
                object obj = ResourceManager.GetObject("JoinableCollectionNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> JoinInfo {
            get {
                object obj = ResourceManager.GetObject("JoinInfo", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Kill {
            get {
                object obj = ResourceManager.GetObject("Kill", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> LoadBubble {
            get {
                object obj = ResourceManager.GetObject("LoadBubble", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> LoadBubbleMounting {
            get {
                object obj = ResourceManager.GetObject("LoadBubbleMounting", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> LoadDirectoryNode {
            get {
                object obj = ResourceManager.GetObject("LoadDirectoryNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> LoadFinalDatabase {
            get {
                object obj = ResourceManager.GetObject("LoadFinalDatabase", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> LoadMetadata {
            get {
                object obj = ResourceManager.GetObject("LoadMetadata", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> LoadMetadataScheduleNode {
            get {
                object obj = ResourceManager.GetObject("LoadMetadataScheduleNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> LoadModuleAssembly {
            get {
                object obj = ResourceManager.GetObject("LoadModuleAssembly", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> LoadPeriodically {
            get {
                object obj = ResourceManager.GetObject("LoadPeriodically", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> LoadProgress {
            get {
                object obj = ResourceManager.GetObject("LoadProgress", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Logging {
            get {
                object obj = ResourceManager.GetObject("Logging", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Lookup {
            get {
                object obj = ResourceManager.GetObject("Lookup", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> LookupCompositeJoinInfo {
            get {
                object obj = ResourceManager.GetObject("LookupCompositeJoinInfo", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Main {
            get {
                object obj = ResourceManager.GetObject("Main", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> MakeProjectSpecificCatalogueNormalAgain {
            get {
                object obj = ResourceManager.GetObject("MakeProjectSpecificCatalogueNormalAgain", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Menu {
            get {
                object obj = ResourceManager.GetObject("Menu", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> NoIconAvailable {
            get {
                object obj = ResourceManager.GetObject("NoIconAvailable", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ObjectExport {
            get {
                object obj = ResourceManager.GetObject("ObjectExport", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ObjectImport {
            get {
                object obj = ResourceManager.GetObject("ObjectImport", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> OrangeIssue {
            get {
                object obj = ResourceManager.GetObject("OrangeIssue", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> OtherPipelinesNode {
            get {
                object obj = ResourceManager.GetObject("OtherPipelinesNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ParametersNode {
            get {
                object obj = ResourceManager.GetObject("ParametersNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> PatientIndexTable {
            get {
                object obj = ResourceManager.GetObject("PatientIndexTable", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> PermissionWindow {
            get {
                object obj = ResourceManager.GetObject("PermissionWindow", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Pipeline {
            get {
                object obj = ResourceManager.GetObject("Pipeline", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> PipelineComponent {
            get {
                object obj = ResourceManager.GetObject("PipelineComponent", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> PipelineComponentArgument {
            get {
                object obj = ResourceManager.GetObject("PipelineComponentArgument", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> PipelineComponentDestination {
            get {
                object obj = ResourceManager.GetObject("PipelineComponentDestination", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> PipelineComponentSource {
            get {
                object obj = ResourceManager.GetObject("PipelineComponentSource", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> PivotField {
            get {
                object obj = ResourceManager.GetObject("PivotField", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Plugin {
            get {
                object obj = ResourceManager.GetObject("Plugin", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> PreLoadDiscardedColumn {
            get {
                object obj = ResourceManager.GetObject("PreLoadDiscardedColumn", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> PreLoadDiscardedColumnsNode {
            get {
                object obj = ResourceManager.GetObject("PreLoadDiscardedColumnsNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ProcessTask {
            get {
                object obj = ResourceManager.GetObject("ProcessTask", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ProcessTaskArgument {
            get {
                object obj = ResourceManager.GetObject("ProcessTaskArgument", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Project {
            get {
                object obj = ResourceManager.GetObject("Project", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ProjectCatalogue {
            get {
                object obj = ResourceManager.GetObject("ProjectCatalogue", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ProjectCataloguesNode {
            get {
                object obj = ResourceManager.GetObject("ProjectCataloguesNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ProjectCohortIdentificationConfigurationAssociation {
            get {
                object obj = ResourceManager.GetObject("ProjectCohortIdentificationConfigurationAssociation", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ProjectCohortIdentificationConfigurationAssociationsNode {
            get {
                object obj = ResourceManager.GetObject("ProjectCohortIdentificationConfigurationAssociationsNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ProjectCohortsNode {
            get {
                object obj = ResourceManager.GetObject("ProjectCohortsNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ProjectSavedCohortsNode {
            get {
                object obj = ResourceManager.GetObject("ProjectSavedCohortsNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ProjectsNode {
            get {
                object obj = ResourceManager.GetObject("ProjectsNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> RedIssue {
            get {
                object obj = ResourceManager.GetObject("RedIssue", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Release {
            get {
                object obj = ResourceManager.GetObject("Release", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ReleaseLog {
            get {
                object obj = ResourceManager.GetObject("ReleaseLog", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> RemoteRDMP {
            get {
                object obj = ResourceManager.GetObject("RemoteRDMP", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> ReOrder {
            get {
                object obj = ResourceManager.GetObject("ReOrder", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> RowCounts_Ignore {
            get {
                object obj = ResourceManager.GetObject("RowCounts_Ignore", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> RowCounts_Respect {
            get {
                object obj = ResourceManager.GetObject("RowCounts_Respect", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> SelectedDataSetsForcedJoin {
            get {
                object obj = ResourceManager.GetObject("SelectedDataSetsForcedJoin", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Spanner {
            get {
                object obj = ResourceManager.GetObject("Spanner", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> SpontaneouslyInventedColumn {
            get {
                object obj = ResourceManager.GetObject("SpontaneouslyInventedColumn", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> SQL {
            get {
                object obj = ResourceManager.GetObject("SQL", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> SqlThenVSNow {
            get {
                object obj = ResourceManager.GetObject("SqlThenVSNow", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> StandardPipelineUseCaseNode {
            get {
                object obj = ResourceManager.GetObject("StandardPipelineUseCaseNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> StandardRegex {
            get {
                object obj = ResourceManager.GetObject("StandardRegex", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> StarHollow {
            get {
                object obj = ResourceManager.GetObject("StarHollow", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> SupplementalExtractionResults {
            get {
                object obj = ResourceManager.GetObject("SupplementalExtractionResults", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> SupportingDocument {
            get {
                object obj = ResourceManager.GetObject("SupportingDocument", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> SupportingDocumentExtractable {
            get {
                object obj = ResourceManager.GetObject("SupportingDocumentExtractable", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> SupportingDocumentExtractableGlobal {
            get {
                object obj = ResourceManager.GetObject("SupportingDocumentExtractableGlobal", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> SupportingDocumentGlobal {
            get {
                object obj = ResourceManager.GetObject("SupportingDocumentGlobal", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> SupportingSqlExtractable {
            get {
                object obj = ResourceManager.GetObject("SupportingSqlExtractable", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> SupportingSqlExtractableGlobal {
            get {
                object obj = ResourceManager.GetObject("SupportingSqlExtractableGlobal", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> SupportingSqlGlobal {
            get {
                object obj = ResourceManager.GetObject("SupportingSqlGlobal", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> SupportingSQLTable {
            get {
                object obj = ResourceManager.GetObject("SupportingSQLTable", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Sync {
            get {
                object obj = ResourceManager.GetObject("Sync", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> TableInfo {
            get {
                object obj = ResourceManager.GetObject("TableInfo", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> TableInfoServerNode {
            get {
                object obj = ResourceManager.GetObject("TableInfoServerNode", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> TableInfoTableValuedFunction {
            get {
                object obj = ResourceManager.GetObject("TableInfoTableValuedFunction", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Tick {
            get {
                object obj = ResourceManager.GetObject("Tick", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> TicketingSystemConfiguration {
            get {
                object obj = ResourceManager.GetObject("TicketingSystemConfiguration", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> TimeCoverageField {
            get {
                object obj = ResourceManager.GetObject("TimeCoverageField", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> TinyGreen {
            get {
                object obj = ResourceManager.GetObject("TinyGreen", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> TinyRed {
            get {
                object obj = ResourceManager.GetObject("TinyRed", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> TinyYellow {
            get {
                object obj = ResourceManager.GetObject("TinyYellow", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> UnfreezeExtractionConfiguration {
            get {
                object obj = ResourceManager.GetObject("UnfreezeExtractionConfiguration", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> UNION {
            get {
                object obj = ResourceManager.GetObject("UNION", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> UNIONCohortAggregate {
            get {
                object obj = ResourceManager.GetObject("UNIONCohortAggregate", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Waiting {
            get {
                object obj = ResourceManager.GetObject("Waiting", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> WaitingForDatabase {
            get {
                object obj = ResourceManager.GetObject("WaitingForDatabase", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> WhatIsACohort {
            get {
                object obj = ResourceManager.GetObject("WhatIsACohort", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> WindowLayout {
            get {
                object obj = ResourceManager.GetObject("WindowLayout", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Writing {
            get {
                object obj = ResourceManager.GetObject("Writing", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> Attacher
        {
            get
            {
                object obj = ResourceManager.GetObject("Attacher", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> DataProvider
        {
            get
            {
                object obj = ResourceManager.GetObject("DataProvider", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type Image.
        /// </summary>
        public static Image<Argb32> MutilateDataTables
        {
            get
            {
                object obj = ResourceManager.GetObject("MutilateDataTables", resourceCulture);
                return ((Image<Argb32>)(obj));
            }
        }
    }
}
