//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rdmp.Core.Icons.IconProvision {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FamFamFamIcons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FamFamFamIcons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rdmp.Core.Icons.IconProvision.FamFamFamIcons", typeof(FamFamFamIcons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] application_home {
            get {
                object obj = ResourceManager.GetObject("application_home", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] arrow_refresh {
            get {
                object obj = ResourceManager.GetObject("arrow_refresh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] bin_closed {
            get {
                object obj = ResourceManager.GetObject("bin_closed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] delete_multi {
            get {
                object obj = ResourceManager.GetObject("delete_multi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] disk {
            get {
                object obj = ResourceManager.GetObject("disk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] flag_red {
            get {
                object obj = ResourceManager.GetObject("flag_red", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] GreenFace {
            get {
                object obj = ResourceManager.GetObject("GreenFace", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] link {
            get {
                object obj = ResourceManager.GetObject("link", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] link_break {
            get {
                object obj = ResourceManager.GetObject("link_break", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] lock_break {
            get {
                object obj = ResourceManager.GetObject("lock_break", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] magnifier {
            get {
                object obj = ResourceManager.GetObject("magnifier", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] page_white_get {
            get {
                object obj = ResourceManager.GetObject("page_white_get", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] page_white_put {
            get {
                object obj = ResourceManager.GetObject("page_white_put", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] page_white_word {
            get {
                object obj = ResourceManager.GetObject("page_white_word", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] pencil_go {
            get {
                object obj = ResourceManager.GetObject("pencil_go", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] phone {
            get {
                object obj = ResourceManager.GetObject("phone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] picture_save {
            get {
                object obj = ResourceManager.GetObject("picture_save", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] RedFace {
            get {
                object obj = ResourceManager.GetObject("RedFace", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] Redo {
            get {
                object obj = ResourceManager.GetObject("Redo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] text_align_left {
            get {
                object obj = ResourceManager.GetObject("text_align_left", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] text_list_bullets {
            get {
                object obj = ResourceManager.GetObject("text_list_bullets", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] tick {
            get {
                object obj = ResourceManager.GetObject("tick", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] time {
            get {
                object obj = ResourceManager.GetObject("time", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] Undo {
            get {
                object obj = ResourceManager.GetObject("Undo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] wand {
            get {
                object obj = ResourceManager.GetObject("wand", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] YellowFace {
            get {
                object obj = ResourceManager.GetObject("YellowFace", resourceCulture);
                return ((byte[])(obj));
            }
        }

        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] Forward {
            get {
                object obj = ResourceManager.GetObject("forward", resourceCulture);
                return ((byte[])(obj));
            }
        }

        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] Back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
