// Copyright (c) The University of Dundee 2018-2019
// This file is part of the Research Data Management Platform (RDMP).
// RDMP is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
// RDMP is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
// You should have received a copy of the GNU General Public License along with RDMP. If not, see <https://www.gnu.org/licenses/>.

using System.Reflection;

namespace CatalogueLibrary.ExternalDatabaseServerPatching
{
    /// <summary>
    /// Documents the relationship between the patching and database assemblies of the Query Caching system of Cohort Builder.  Query caching is how we handle
    /// SET operations (INTERSECT / UNION / EXCEPT) between many large complex subqueries which would not execute efficiently in Sql Server.  The Query cache
    /// records the SQL generated by CohortQueryBuilder and the resulting identifier list with an index so that set operations can be redirected to the cache
    /// and execute at lightning speed.
    /// </summary>
    public class QueryCachingDatabasePatcher:IPatcher
    {
        /// <inheritdoc/>
        public Assembly GetHostAssembly()
        {
            return Assembly.Load("QueryCaching");
        }

        /// <inheritdoc/>
        public Assembly GetDbAssembly()
        {
            return Assembly.Load("QueryCaching.Database");
        }
    }
}