name: Build RDMP Docker Image
on:
  push:

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Build RDMP and container
        run: |
          dotnet publish Tools/rdmp/rdmp.csproj  -c Release --nologo -o rdmp-cli -r linux-x64 --sc true -v q -p:PublishReadyToRun=true -p:PublishSingleFile=true
          ctr=$(buildah from docker://public.ecr.aws/ubuntu/ubuntu:20.04_stable)
          buildah copy "$ctr" rdmp-cli /rdmp/
          buildah run "$ctr" sh << EOS
          set -e
          apt-get update -qq
          apt-get install -qqy curl gnupg2 python3 ca-certificates --no-install-recommends
          curl https://packages.microsoft.com/keys/microsoft.asc
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 apt-key add -
          curl -sL https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-preview.list >> /etc/apt/sources.list
          apt-get update -qq
          apt-get install -qqy mssql-server --no-install-recommends
          ln /bin/true /bin/systemctl
          curl -sL https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl3.py > /usr/bin/systemctl
          chmod +x /usr/bin/systemctl 
          MSSQL_PID=Express ACCEPT_EULA=Y MSSQL_SA_PASSWORD='YourStrong#Passw0rd' /opt/mssql/bin/mssql-conf -n setup
          /rdmp/rdmp install -u sa -p 'YourStrong#Passw0rd' -e RDMPDock_
          cat <<EOT > /rdmp/Databases.yaml
          CatalogueConnectionString: Server=localhost;user=SA;password=YourStrong#Passw0rd;Database=RDMPDock_Catalogue;
          DataExportConnectionString: Server=localhost;user=SA;password=YourStrong#Passw0rd;Database=RDMPDock_DataExport;
          EOT
          EOS
          buildah config --cmd "/usr/bin/systemctl" "$ctr"
          buildah commit "$ctr" "rdmpcli"
      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io/jas88
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push mini-container to GitHub Container Repository
        id: push-mini-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: rdmpcli
          tags: latest
          registry: ghcr.io/hicservices
